# Generated by Django 5.1.3 on 2024-12-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicationId", models.CharField(max_length=10, unique=True)),
                ("fullName", models.CharField(max_length=100)),
                ("motherName", models.CharField(max_length=100)),
                ("dateOfBirth", models.DateField()),
                ("nationality", models.CharField(max_length=15)),
                ("category", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=400)),
                ("marksOf10th", models.DecimalField(decimal_places=2, max_digits=5)),
                ("marksOf12th", models.DecimalField(decimal_places=2, max_digits=5)),
                ("schoolOf10th", models.CharField(max_length=200)),
                ("collegeIf12th", models.CharField(max_length=200)),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="student.studentcredentials",
                        to_field="email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photoAndSignature", models.ImageField(upload_to="documents/photos/")),
                (
                    "marksheetOf10th",
                    models.ImageField(upload_to="documents/10th_marksheets/"),
                ),
                (
                    "marksheetOf12th",
                    models.ImageField(upload_to="documents/12th_marksheets/"),
                ),
                (
                    "cetScoreCard",
                    models.ImageField(upload_to="documents/cet_scorecards/"),
                ),
                ("schoolLC", models.ImageField(upload_to="documents/school_lcs/")),
                ("collegeLC", models.ImageField(upload_to="documents/college_lcs/")),
                (
                    "casteCertificate",
                    models.ImageField(upload_to="documents/caste_certificates/"),
                ),
                (
                    "casteValidityCertificate",
                    models.ImageField(
                        upload_to="documents/caste_validity_certificates/"
                    ),
                ),
                (
                    "domicileCertificate",
                    models.ImageField(upload_to="documents/domicile_certificates/"),
                ),
                (
                    "incomeCertificate",
                    models.ImageField(upload_to="documents/income_certificates/"),
                ),
                (
                    "nonCreamyLayerCertificate",
                    models.ImageField(
                        upload_to="documents/non_creamy_layer_certificates/"
                    ),
                ),
                ("aadharCard", models.ImageField(upload_to="documents/aadhar_cards/")),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="student.studentcredentials",
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
