# Generated by Django 5.1.3 on 2024-12-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_studentdocuments_aadharcardverified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdetails",
            name="fullName",
        ),
    ]
