# Generated by Django 5.1.3 on 2024-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_studentdocuments_aadharcard_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdetails",
            old_name="collegeIf12th",
            new_name="collegeOf12th",
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="aadharCardReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="casteCertificateReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="casteValidityCertificateReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="cetScoreCardReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="collegeLCReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="domicileCertificateReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="incomeCertificateReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="marksheetOf10thReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="marksheetOf12thReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="nonCreamyLayerCertificateReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="photoAndSignatureReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="studentdocuments",
            name="schoolLCReason",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="aadharCardVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="casteCertificateVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="casteValidityCertificateVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="cetScoreCardVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="collegeLCVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="domicileCertificateVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="incomeCertificateVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="marksheetOf10thVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="marksheetOf12thVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="nonCreamyLayerCertificateVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="photoAndSignatureVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="schoolLCVerified",
            field=models.CharField(default="padding", max_length=10),
        ),
    ]
