# Generated by Django 5.1.3 on 2024-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_rename_collegeif12th_studentdetails_collegeof12th_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocuments",
            name="casteCertificateVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="casteValidityCertificateVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="cetScoreCardVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="collegeLCVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="domicileCertificateVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="incomeCertificateVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="marksheetOf10thVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="marksheetOf12thVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="nonCreamyLayerCertificateVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="photoAndSignatureVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="schoolLCVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
