# Generated by Django 5.1.3 on 2024-12-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_studentdocuments_castecertificateverified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcredentials",
            name="id",
        ),
        migrations.AlterField(
            model_name="studentcredentials",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="student.studentcredentials",
            ),
        ),
        migrations.AlterField(
            model_name="studentdocuments",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="student.studentcredentials",
            ),
        ),
    ]
