# Generated by Django 5.1.3 on 2024-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_remove_studentcredentials_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocuments",
            name="aadharCardVerified",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
